### Work with arrays using numpy

In [1]:
# import libray
import numpy as np

In [2]:
# One dimension array
arr1 = np.array([1,2,3, np.nan], dtype=float)

In [3]:
# multi Dimension array
arr2 = np.array([
    [1,2,3,8],
    [4,5,6,67],
    [7,14,8, 45]
])

In [4]:
# Check the shape of array (number of rows and columns)
arr2.shape

(3, 4)

In [5]:
# check data type 
arr2.dtype

dtype('int64')

In [6]:
# sum all element of array by 2

arr2 = arr2 + 2
arr2

array([[ 3,  4,  5, 10],
       [ 6,  7,  8, 69],
       [ 9, 16, 10, 47]])

In [7]:
#maximum value of array
arr2.max()

np.int64(69)

In [8]:
# minimum value of array
arr2.min()

np.int64(3)

In [9]:
# average or mean 
arr2.mean()

np.float64(16.166666666666668)

In [10]:
# sqrt of each element
print(np.sqrt(arr2))

[[1.73205081 2.         2.23606798 3.16227766]
 [2.44948974 2.64575131 2.82842712 8.30662386]
 [3.         4.         3.16227766 6.8556546 ]]


In [11]:
# replace the value of index 3 
arr1[3] = 89


In [12]:
arr1

array([ 1.,  2.,  3., 89.])

In [13]:
# concatenate arrays

np.concatenate((arr1 , arr2.ravel()))

array([ 1.,  2.,  3., 89.,  3.,  4.,  5., 10.,  6.,  7.,  8., 69.,  9.,
       16., 10., 47.])

In [14]:
# Transpose array interchange of rows and columns
np.transpose(arr2)

array([[ 3,  6,  9],
       [ 4,  7, 16],
       [ 5,  8, 10],
       [10, 69, 47]])

In [15]:
#  Generate random number of each element of rows and columns
arr3 =np.array(np.random.rand(2,4))
arr3

array([[0.73409281, 0.22255419, 0.99184874, 0.87341664],
       [0.48710226, 0.919275  , 0.99052852, 0.233439  ]])